### ISSUE TITLE
SERVERDATA_EXECCOMMAND response timeout.

### ISSUE THREAD

**Issue by Nols1000** [smhxx/srcds-tools#1] opened 2015-12-22 23:21 UTC
I get a AUTH-response. But if I send a exec-command-request later, I dont get a response.

```js
***>node test
send RConRequest {
  domain: null,
  _events: { done: [Function] },
  _eventsCount: 1,
  _maxListeners: undefined,
  type: 3,
  id: 0,
  body: 'AUTH-CODE',
  readResponse: [Function],
  startTimeout: [Function],
  toBuffer: [Function],
  getID: [Function],
  getType: [Function] }

respons RConResponse {
  type: 0,
  id: 0,
  body: '',
  isTerminator: [Function],
  isFailedAuthResponse: [Function],
  size: [Function] }

respons RConResponse {
  type: 2,
  id: 0,
  body: '',
  isTerminator: [Function],
  isFailedAuthResponse: [Function],
  size: [Function] }

readResponse AUTH RESPONSE
Authenticated successfully!
send RConRequest {
  domain: null,
  _events: { done: [Function] },
  _eventsCount: 1,
  _maxListeners: undefined,
  type: 2,
  id: 1,
  body: 'sv_cheats 1',
  readResponse: [Function],
  startTimeout: [Function],
  toBuffer: [Function],
  getID: [Function],
  getType: [Function] }


***\node_modules\srcds-tools\lib\rcon\RConRequest.js:77
                        throw new RConTimeoutError("An RCON request failed because the operation timed out after " + duration + "ms.");
                        ^
 RConTimeoutError: An RCON request failed because the operation timed out after 1000ms.
    at Error.RConTimeoutError (***\node_modules\srcds-tools\lib\errors\RConTimeoutError.js:4:8)
    at null._onTimeout (***\node_modules\srcds-tools\lib\rcon\RConRequest.js:77:10)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by smhxx** [comment] 2015-12-24 08:12
Hey there! Thanks for opening the issue. I haven't used or updated the library in a while, so I wasn't actually aware this was happening. I did some poking around myself and managed to reproduce a similar bug; this appears to be a regression caused by an update to srcds that I wasn't aware of. It appears that the error is being thrown because the server is closing the socket prematurely. It isn't immediately clear to me why the socket is being closed immediately after authentication, but I may be able to get to the root cause of it with some investigation.

Just looking at the output of your test code, I'm already seeing some weird stuff going on. For one, I've got absolutely no clue what that first `{ type: 0, id: 0, body: ''}` response is. I don't think the server should be sending that at all, if I remember correctly. The ID of that packet is the same as the next response, so it's obviously also in response to the auth request, but it's not yet clear to me why it's sending 2 responses at all. As far as I remember, it used to only send one. I'll take a look at it tonight and see what I can figure out.

**Comment by smhxx** [comment] 2015-12-24 12:36
I've done some snooping around in the packets and isolated the issue, which as far as I can tell appears to be an undocumented change in the srcds RCON protocol. I still don't know when the change was made, but this pretty clearly shows what's going on:

```js
> rcon.connect("192.168.1.5")
Connected to server 192.168.1.5:27015.
> rcon.sendPassword("wrongpass")
Sending request packet:
  ID: 0
  Type: AUTH_REQUEST (3)
  Body: 'wrongpass'
  Total Size: 23                Payload Size:9
  Is terminator?  no            Is failed auth response?  no

Received response packet:
  ID: 0
  Type: EXEC_RESPONSE (0)
  Body: ''
  Total Size: 14                Payload Size:0
  Is terminator?  yes           Is failed auth response?  no

Received response packet:
  ID: -1
  Type: EXEC_REQUEST / AUTH_RESPONSE (2)
  Body: ''
  Total Size: 14                Payload Size:0
  Is terminator?  no            Is failed auth response?  yes

TypeError: Cannot read property 'readResponse' of undefined
    at Socket.readResponsePacket (C:\Users\Ryan\github\srcds-tools\lib\rcon\RCon
Client.js:119:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
	
> rcon.sendPassword("rightpass")
Sending request packet:
  ID: 1
  Type: AUTH_REQUEST (3)
  Body: 'rightpass'
  Total Size: 23                Payload Size:9
  Is terminator?  no            Is failed auth response?  no

Received response packet:
  ID: 1
  Type: EXEC_RESPONSE (0)
  Body: ''
  Total Size: 14                Payload Size:0
  Is terminator?  yes           Is failed auth response?  no

Received response packet:
  ID: 1
  Type: EXEC_REQUEST / AUTH_RESPONSE (2)
  Body: ''
  Total Size: 14                Payload Size:0
  Is terminator?  no            Is failed auth response?  no
```

Regardless of whether the password is correct or not, the server is sending an empty EXEC_RESPONSE prior to the AUTH_RESPONSE. I honestly have no clue why they would make this change, but I'm assuming it wasn't recent. The bug in `srcds-tools` is caused by the fact that the EXEC_RESPONSE comes *before* the AUTH_RESPONSE. The code is satisfied by the fact that it received a response, and "forgets" about the AUTH_REQUEST it sent. Then, when the actual AUTH_RESPONSE comes in, the code has no idea what AUTH_REQUEST it goes with, since the only AUTH_REQUEST it ever sent was already responded to. The fix should be one line of code.

I'm going to push a version 1.2.0 right now, but I'll leave the issue open until you confirm that it's fixed the problem you were having. I'm actually off to the airport in about an hour and I haven't packed yet, so I can't really do much more today. I'll test the fix as soon as I am able to do so, which may be as soon as tonight. Thank you so much for your assistance with this! I hope whatever you're planning on using `srcds-tools` for goes well!

**Closed** 2015-12-31 00:45 UTC
Labels: critical bug, regression, resolved
